[config]
  csp-hash-required = true

[[headers]]
# Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    x-Content-Type-Options = "nosniff"
    ReFerrer-Policy = "same-origin"
    Strict-Transport-Security = "max-age=63072000"

[[headers]]
  for = "/"

  [headers.values]
    cache-control = """\
      public, \
      max-age=10m, \
      stale-while-revalidate=10m"""
  
  # ########################### CSP ################################
  [headers.Content-Security-Policy]
    for = "index.html"

    [headers.Content-Security-Policy.values]
      default-src = "'self'"
      script-src = "'self'"
      style-src = "'self'"


# Static assets
[[headers]]
  for = "/internal/immutable/*"

  [headers.values]
  # Long cache for immutable assets.
  # All files are hashed therfore can be cache busted. 
    cache-control = """\
      public, \
      max-age=1y"""
